### ISSUE TITLE
[BUG]: ScanProcessor$: Error while guessing language

### ISSUE THREAD

**Issue by PsyLogic** [Privado-Inc/privado-cli#58] opened 2023-11-02 11:32 UTC
**Describe the Bug**
Following the instructions of how to scan a directory but it fails
https://docs.privado.ai/tutorials/command-reference

**Expected Behavior**
Same results as described in the instructions

**To Reproduce**
1. Specify the OS and version: WIN 11
3. Specify repository link if possible: https://github.com/saurabh-sudo/BankingSystem-Backend
4. Detailed steps to reproduce the issue:
```
curl -o- https://raw.githubusercontent.com/Privado-Inc/privado-cli/main/install.sh | bash
git clone git@github.com:saurabh-sudo/BankingSystem-Backend.git
privado scan BankingSystem-Backend/BankData/
```

**Screenshots**
![image](https://github.com/Privado-Inc/privado-cli/assets/8070135/ed3cc932-5c02-4286-9ec4-32dff83c962e)

**Additional Context**
Privado CLI Version: v2.2.7
Privado Core Version: 1.1.99
Privado Language Engine Version: 2.0.134

**Comment by pandurangpatil** [comment] 2024-01-22 11:17
@PsyLogic can't reproduce this issue with the given repository path. It could detect the language as Java and finish the scan. If I understand correctly, there was an issue when we use the relative path of the repo to be scanned instead of the complete path. Which seems to be fixed in the recent version. 

```
git clone git@github.com:saurabh-sudo/BankingSystem-Backend.git
privado scan BankingSystem-Backend/BankData/
```

**Closed by pandurangpatil** 2024-01-22 11:17 UTC
Labels: bug
